### ISSUE TITLE
Alphabet length

### ISSUE THREAD

**Issue by rionbr** [dit/dit#119]
First, thanks for the great package!

I believe the length of the alphabet is currently only 1 character long. (ex: 'H'eads or 'T'ails). This can cause some issues when the alphabet needs to longer.

In my case, I have a network in time, and I'm treating each node as a random variable. And I'm easily running out of 1 length characters.

```python
>>> n = ['a', 'b', 'c']
>>> v = [.1, .4, .5,]

>>> dit.Distribution(n,v)
Class:          Distribution
Alphabet:       ('a', 'b', 'c') for all rvs
Base:           linear
Outcome Class:  str
Outcome Length: 1
RV Names:       None

x   p(x)
a   0.1
b   0.4
c   0.5
```

```python
>>> n = ['a', 'b', 'c', 'za']
>>> v = [.1, .4, .4, .1]

>>> print dit.Distribution(n,v)
dit.exceptions.ditException: Not all outcomes have the same length.
```
Is there a workaround? Thanks!
=]

**Comment by rionbr** [comment]
Found a way by looking into the source code of the examples.

```python
n = [('a1','0'), ('b2','1'), ('c3','0'), ('z4','1')]
v = [.1, .4, .4, .1]

>>> dit.Distribution(n,v)
Class:          Distribution
Alphabet:       (('a', 'b', 'c', 'z'), ('0', '1'))
Base:           linear
Outcome Class:  tuple
Outcome Length: 2
RV Names:       None

x            p(x)
('a1', '0')   0.1
('b2', '1')   0.4
('c3', '0')   0.4
('z4', '1')   0.1
```

Hopefully this will help others.
Thanks! =]

**Comment by Autoplectic** [comment]
Yes, sorry this is not more clear. I will improve the documentation shortly.

The issue you were seeing is that strings are also containers in python, so it seemed like you were constructing joint events over different dimensions. Another possibility is:

    n = [('x0',), ('x1',), ('x10',)]
