### ISSUE TITLE
Unspecified requirement during installation

### ISSUE THREAD

**Issue by wuhaochen** [dit/dit#131]
Hi there,
It seems scipy is not really an optional dependency. When I run a fresh install and tried to import dit. I got the following error:

> import dit
> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
>   File "/home/hcwu/python_virtual/dit_test/lib/python2.7/site-packages/dit/__init__.py", line 29, in <module>
>     from .algorithms import pruned_samplespace, expanded_samplespace
>   File "/home/hcwu/python_virtual/dit_test/lib/python2.7/site-packages/dit/algorithms/__init__.py", line 12, in <module>
>     from .scipy_optimizers import *
>   File "/home/hcwu/python_virtual/dit_test/lib/python2.7/site-packages/dit/algorithms/scipy_optimizers.py", line 16, in <module>
>     from scipy.optimize import basinhopping, minimize
> ImportError: No module named scipy.optimize

**Comment by Autoplectic** [comment]
made scipy a requirement.
