### ISSUE TITLE
Undefined latex commands in documentation

### ISSUE THREAD

**Issue by stsievert** [dit/dit#145]
On the page https://dit.readthedocs.io/en/latest/notation.html, for all the browsers I tried, including a version of Chrome that's unmodified (no plugins).

The undefined commands show in red text. The red text I see are

* `\H`
* `\ind`
* `\imore`, `\iless`, `\ieq`
* `\join`, `\meet`
* `\mss`

<img width="1280" alt="screen shot 2018-05-20 at 6 07 09 pm" src="https://user-images.githubusercontent.com/1320475/40284705-a28080ac-5c82-11e8-8d0f-b88cc23d001e.png">

**Comment by stsievert** [comment]
I would suggest including a `commands.rst` file that defines all the commands in MathJax and is included in every file.

**Comment by stsievert** [comment]
Poking around more, I see that

* `\I`, `\H`, `\DKL` undefined on https://dit.readthedocs.io/en/latest/rate_distortion.html#
* `\I` undefined on https://dit.readthedocs.io/en/latest/profiles.html
* `\H`, `\I` undefined on https://dit.readthedocs.io/en/latest/measures/shannon.html

**Comment by Autoplectic** [comment]
looks like our custom defs (docs/_static/dit_mathjax.js) aren't getting loaded by mathjax. i'm looking into it.

**Comment by Autoplectic** [comment]
this seems to have been fixed by updating the cdn for mathjax in the sphinx conf.

**Comment by Autoplectic** [comment]
this seems to work at docs.dit.io, but not at dit.readthedocs.io

**Comment by stsievert** [comment]
I think that's acceptable to only having it working at the official (docs docs.dit.io) and not the other site (dit.readthedocs.io)
