### ISSUE TITLE
Output table

### ISSUE THREAD

**Issue by fabioanza** [dit/dit#151]
I was running the examples in the documentation. In particular, the example of a 6-sided die with a uniform probability distribution. Following closely the code written in "Playing with ScalarDistribution", when typing in d6+d6, the output table had some issues. When the alphabet reaches number 10 (two digits) the first digit ("1") is correctly aligned to the other elements of the alphabet while the second one ("0") is not. For example it should look like
| x | p(x) |
| 10 | some p(10) |
while what it does is like
| x | p(x) |
| 1 | 0 | p(10)|
where the corresponding rows have more column, to accommodate the fact that the two digits of one element of the alphabet are going into different columns.

**Comment by Autoplectic** [comment]
fixed in b4c75f3d7b91a1c852835276b6124d9b88463640
