### ISSUE TITLE
numpy.ndarray' object has no attribute 'is_joint' 

### ISSUE THREAD

**Issue by talhaanwarch** [dit/dit#154]
I am getting an error 'numpy.ndarray' object has no attribute 'is_joint'' while applying Renyi entropy. May b i am unable to get what is 'dist'. Can you explain it

**Comment by Autoplectic** [comment]
can you provide an example of the code that is failing?

a dist is, general, an instance of dit.Distribution. For example:

    import dit
    from dit.other import renyi_entropy

    dist = dit.Distribution(['0', '1', '2'], [1/3, 1/6, 1/2])

    renyi_entropy(dist, order=3)

    1.292481250360578
