### ISSUE TITLE
AttributeError: 'DiGraph' object has no attribute 'node'

### ISSUE THREAD

**Issue by zuiyanzuiyan** [dit/dit#202]
I'm getting an error when running pid.py under the dit module.

~/anaconda3/lib/python3.9/site-packages/dit/pid/pid.py in get_partial(self, node)
    245             The partial information associated with `node`.
    246         """
--> 247         return self._lattice.node[node]['pi']
    248 
    249     def to_string(self, digits=4):

AttributeError: 'DiGraph' object has no attribute 'node'

And the error appears to be with the networkx package.
Running Python v3.9.1 and here are the dependencies installed:

dit = 1.2.3
networkx  = 3.0

I've seen that other repositories have run into similar problems. However, if I try solutions such as pinning networkx==1.11, I run into other errors:

ImportError: cannot import name 'gcd' from 'fractions'

**Comment by Autoplectic** [comment]
sorry for the super late reply.  This was fixed a long time ago, upgrade your version of dit to 1.5 or checkout the current dev version and things should work fine.
