### ISSUE TITLE
use Enum for rv type

### ISSUE THREAD

**Issue by Autoplectic** [dit/dit#40]
use Enum on py3.4+ and the backported enum34 package on all others.

at the moment this would be:

class RV_mode(Enum):
    names = 0
    indices = 1

and each dist would grow a type which is one of these enums. Information measures would look at this property to know how to do things.

**Comment by chebee7i** [comment]
Addressed in #71.

**Comment by chebee7i** [comment]
And also in bffa2c6f8274d7ea6ba3f001f413cdc93434a826 from a while back.
