### ISSUE TITLE
doctests

### ISSUE THREAD

**Issue by chebee7i** [dit/dit#49]
We need to run doctests for the manually written portions of the documentation.   Probably at doc-build time? The doctests in the function/class docstrings should be tested already.

**Comment by Autoplectic** [comment]
This is covered by the ipython directive and the doctest decorator, yes?

**Comment by chebee7i** [comment]
Yeah this could be fixed already. Originally there was a disconnect and some of the manually written documentation was not in sync with the current code (or the output was incorrect). So if it is all using @doctest now, then yeah this is done.
