### ISSUE TITLE
Estimators of H, I

### ISSUE THREAD

**Issue by chebee7i** [dit/dit#52]
(Possibly) add some estimators of entropy, mutual information, etc.

See for example:

Jean Hausser, Korbinian Strimmer, "Entropy inference and the James-Stein estimator, with application to nonlinear gene association networks". http://arxiv.org/abs/0811.3579

Also see DeDeo's recent papers:

   http://dx.doi.org/10.3390/e15114668
   http://dx.doi.org/10.3390/e15062246

and [THOTH](http://tuvalu.santafe.edu/~simon/page7/page7.html).  We'll have to think more about how dit should interact with THOTH.

**Comment by Autoplectic** [comment]
also: http://arxiv.org/abs/1503.05911

**Comment by Autoplectic** [comment]
several have been added to dit.inference.

**Comment by Autoplectic** [comment]
however, some fancier ones, like those linked by @chebee7i, are still needed.
