### ISSUE TITLE
Remove support for 2.6

### ISSUE THREAD

**Issue by chebee7i** [dit/dit#74]
Perhaps it's time to say bye-bye to 2.6? There's a decent amount of stuff that would need cleaning up, especially with some of the utils, but it should be relatively straight-forward.

**Comment by Autoplectic** [comment]
i'm 110% in support of this.

various things to look for:
- use of dict() or otherwise in place of dictionary comprehensions
- better asserts in nose.tools
- set comprehensions and set literals
