### ISSUE TITLE
Error while installing on windows 10

### ISSUE THREAD

**Issue by abhigenie92** [dit/dit#90]
creating build\lib.win-amd64-2.7\dit\other\tests
    copying dit\other\tests\__init__.py -> build\lib.win-amd64-2.7\dit\other\tests
    copying dit\other\tests\test_cumulative_residual_entropy.py -> build\lib.win-amd64-2.7\dit\other\tests
    copying dit\other\tests\test_extropy.py -> build\lib.win-amd64-2.7\dit\other\tests
    copying dit\other\tests\test_perplexity.py -> build\lib.win-amd64-2.7\dit\other\tests
    copying dit\other\tests\test_renyi_entropy.py -> build\lib.win-amd64-2.7\dit\other\tests
    copying dit\other\tests\test_tsallis_entropy.py -> build\lib.win-amd64-2.7\dit\other\tests
    creating build\lib.win-amd64-2.7\dit\shannon\tests
    copying dit\shannon\tests\__init__.py -> build\lib.win-amd64-2.7\dit\shannon\tests
    copying dit\shannon\tests\test_shannon.py -> build\lib.win-amd64-2.7\dit\shannon\tests
    creating build\lib.win-amd64-2.7\dit\utils\tests
    copying dit\utils\tests\__init__.py -> build\lib.win-amd64-2.7\dit\utils\tests
    copying dit\utils\tests\test_bindargs.py -> build\lib.win-amd64-2.7\dit\utils\tests
    copying dit\utils\tests\test_bindargs3.py -> build\lib.win-amd64-2.7\dit\utils\tests
    copying dit\utils\tests\test_context.py -> build\lib.win-amd64-2.7\dit\utils\tests
    copying dit\utils\tests\test_latexarray.py -> build\lib.win-amd64-2.7\dit\utils\tests
    copying dit\utils\tests\test_misc.py -> build\lib.win-amd64-2.7\dit\utils\tests
    running build_ext
    cythoning dit/math/_close.pyx to dit/math\_close.c
    building 'dit.math._close' extension
    creating build\temp.win-amd64-2.7
    creating build\temp.win-amd64-2.7\Release
    creating build\temp.win-amd64-2.7\Release\dit
    creating build\temp.win-amd64-2.7\Release\dit\math
    C:\Users\sony\AppData\Local\Programs\Common\Microsoft\Visual C++ for Python\9.0\VC\Bin\amd64\cl.exe /c /nologo /Ox /MD /W3 /GS- /DNDEBUG -IC:\Anaconda\include -IC:\Anaconda\PC /Tcdit/math\_close.c /Fobuild\temp.win-amd64-2.7\Release\dit/math\_close.obj
    _close.c
    dit/math\_close.c(690) : warning C4013: 'isnan' undefined; assuming extern returning int
    dit/math\_close.c(721) : warning C4013: 'isinf' undefined; assuming extern returning int
    C:\Users\sony\AppData\Local\Programs\Common\Microsoft\Visual C++ for Python\9.0\VC\Bin\amd64\link.exe /DLL /nologo /INCREMENTAL:NO /LIBPATH:C:\Anaconda\libs /LIBPATH:C:\Anaconda\PCbuild\amd64 /EXPORT:init_close build\temp.win-amd64-2.7\Release\dit/math\_close.obj /OUT:build\lib.win-amd64-2.7\dit\math\_close.pyd /IMPLIB:build\temp.win-amd64-2.7\Release\dit/math\_close.lib /MANIFESTFILE:build\temp.win-amd64-2.7\Release\dit/math\_close.pyd.manifest
    _close.obj : warning LNK4197: export 'init_close' specified multiple times; using first specification
       Creating library build\temp.win-amd64-2.7\Release\dit/math\_close.lib and object build\temp.win-amd64-2.7\Release\dit/math\_close.exp
    _close.obj : error LNK2019: unresolved external symbol isinf referenced in function __pyx_pf_3dit_4math_6_close_close
    _close.obj : error LNK2019: unresolved external symbol isnan referenced in function __pyx_pf_3dit_4math_6_close_close
    build\lib.win-amd64-2.7\dit\math\_close.pyd : fatal error LNK1120: 2 unresolved externals
    error: command 'C:\\Users\\sony\\AppData\\Local\\Programs\\Common\\Microsoft\\Visual C++ for Python\\9.0\\VC\\Bin\\amd64\\link.exe' failed with exit status 1120

    ----------------------------------------
Command "C:\Anaconda\python.exe -c "import setuptools, tokenize;__file__='c:\\users\\sony\\appdata\\local\\temp\\pip-6hyez5-build\\setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record c:\users\sony\appdata\local\temp\pip-kq1bpj-record\install-record.txt --single-version-externally-managed --compile" failed with error code 1 in c:\users\sony\appdata\local\temp\pip-6hyez5-build

**Comment by Autoplectic** [comment]
perhaps we should hook up AppVeyor to do testing on windows?

i'm guessing windows might break a number of the utils things, but it shouldn't be too hard to get it fixed up.
